baseURL = "https://example.com"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The browser tab name
title = "WAVE - Western Agriculture Variety Explorer"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/cover-image.jpg"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = true

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "WAVE - Western Agriculture Variety Explorer"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "A hub for exploring variety testing data for crops important to the Pacific Northwest, including wheat, barley, canola, lentils, dry peas, and chickpeas."

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© University of Idaho"

<<<<<<< HEAD
  # skill section
  [[params.block]]
    id = "outputs"
    type = "list"
    title = "Our Goals"
    description = "We aim to provide an online database open to all members of the public to explore current and historical variety testing data sets with the ability to filter, query, and download data. Analytical summaris of trials will be in industry-focused apps for each crop. View our wheat database [here](https://vartestdb.nkn.uidaho.edu/)"
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "pic02.jpg"

#    [[params.block.item]]
#      icontype = "fas"
#      icon = "fa-seedling"
#      title = "current trials"

#   [[params.block.item]]
#      icontype = "fas"
#      icon = "fa-list"
#      title = "historic data"

    [[params.block.item]]
      icontype = "fas"
      icon = "fa-database"
      title = "wheat database"
      link = "https://vartestdb.nkn.uidaho.edu/"

#    [[params.block.item]]
#      icontype = "fas"
#      icon = "fa-chart-bar"
#      title = "wheat demo app"
#      link = "https://jpiaskowski.shinyapps.io/idaho_vartest_shiny_app/"

  # participants section
  [[params.block]]
    id = "people"
    type = "list"
    title = "Project Participants"
    description = "**Data contributers:**  [Jim Davis](https://www.uidaho.edu/cals/plant-sciences/our-people/jim-davis), [Juliet M. Marshall](https://www.uidaho.edu/cals/plant-sciences/our-people/juliet-marshall), [Kurtis Schroeder](https://www.uidaho.edu/cals/plant-sciences/our-people/kurtis-schroeder), [Doug Finkelnburg](https://www.uidaho.edu/extension/county/nez-perce/agriculture) and [Olga Walsh](https://www.uidaho.edu/cals/plant-sciences/our-people/olga-walsh) of the University of Idaho; [Steve Jones](https://breadlab.wsu.edu/), [Clark Neely](https://css.wsu.edu/people/faculty/clark-neely/), and [Steve Van Vleet](https://extension.wsu.edu/whitman/agriculture/) of Washington State University; [Ryan Graebner](https://cropandsoil.oregonstate.edu/users/ryan-graebner) of Oregon State University; Kim Garland Campbell, Xiaming Chen and Camille Steber of the USDA-ARS. \n\n **Data curators:**  Jacqueline Tay and Emily Galvin \n\n **Web applications architect:**  [Jennifer Hinds](https://hpc.uidaho.edu/general/Staff/) \n\n **Project Director:**  [Julia Piaskowski](https://www.uidaho.edu/cals/statistical-programs/people/julia-piaskowski)"
    # the picture is stored at static/images/
    picture = "pic03.jpg"
=======
    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = false

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false
>>>>>>> hugo_scroll
    
    [params.meta]
        keywords = "wheat, variety testing, cultivar, Pacific Northwest, database"
