baseurl: 
languageCode: en-us
title: Highlights
theme: hugo-highlights-theme
googleAnalytics: ''
params:
  backgroundpersection: yes
  block:
  
    - buttontext: next
      description: Home of the Western Agriculture Variety Explorer, a hub for exploring variety testing data for crops important to the Pacific Northwest. Currently, this includes wheat, barley, canola, lentils, dry peas, and chickpeas. 
      id: about
      picture: pic01.jpg
      title: About
      type: text
      
    - buttontext: next
      description: This is a multi-state effort to make current and historic variety testing data available to producers, researchers, agriculture professionals and anyone else interested in these data sets. The data will be available in searchable database with an accompanying API and crop-specific apps for trial exploration and visualization. 
# icon list: https://fontawesome.com/search?m=free
      id: skills
      item:
        - icon: fa-seedling
          icontype: fas
          title: current trials
          
        - icon: fa-list
          icontype: fas
          title: historic data
          
        - icon: fa-database
          icontype: fas
          title: database access
          
        - icon: fa-chart-bar
          icontype: fas
          title: visuals
 
    - buttontext: next
      description: All the peeps. 
      id: people
      picture: pic02.jpg
      title: What We Are Doing
      type: text

      
    # - buttontext: next
    #   description: Home of the Western Agriculture Variety Explorer, a hub for exploring variety testing data for crops important to the Pacific Northwest. Currently, this includes wheat, barley, canola, lentils, dry peas, and chickpeas. 
    #   id: about
    #   picture: pic03.jpg
    #   title: P
    #   type: text
      
    - form:
        buttontext: send message
        email: Your Email
        message: Your Message
        name: Name
      id: contact
      picture: pic05.jpg
      title: Get in Touch
      type: contact
  description: 
  email: jpiaskowski@uidaho.edu
  footer:
    enable: yes
    copyright:
      notice:
#        - text: © Untitled
        - text: 'Website build with [hugo](https://gohugo.io/) and [HTML5UP](//html5up.net) theme.'
#        - text: 'Demo Images: [Unsplash](//unsplash.com/)'
    social:
      # - icon: fa-twitter
      #   link: '#'
      #   title: Twitter
      # - icon: fa-facebook
      #   link: '#'
      #   title: Facebook
      # - icon: fa-instagram
      #   link: '#'
      #   title: Instagramm
      # - icon: fa-dribbble
      #   link: '#'
      #   title: Dribbble
      - icon: fa-envelope
        link: '#'
        title: Email
    social_list:
      enable: yes
  hero:
    buttontext: more
    description: Future Home of the Western Agriculture Variety Explorer
    title: Highlights
    type: hero
  name: WAVE
